// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyU12pFAUXOSnZaAV1yblw83h22T9YTkI',
    appId: '1:250433057760:web:cee1e2c212a14e4cc2f185',
    messagingSenderId: '250433057760',
    projectId: 'rota-escolar-7c046',
    authDomain: 'rota-escolar-7c046.firebaseapp.com',
    databaseURL: 'https://rota-escolar-7c046-default-rtdb.firebaseio.com',
    storageBucket: 'rota-escolar-7c046.firebasestorage.app',
    measurementId: 'G-5DWE2ZSR7G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKVR-WRuZ0yPF-slXKGO67jPwRrSnyQFI',
    appId: '1:250433057760:android:7b04c1385db9a2fcc2f185',
    messagingSenderId: '250433057760',
    projectId: 'rota-escolar-7c046',
    databaseURL: 'https://rota-escolar-7c046-default-rtdb.firebaseio.com',
    storageBucket: 'rota-escolar-7c046.firebasestorage.app',
  );

}